### ISSUE TITLE
incorrect permission issue and corrupted file structure

### ISSUE THREAD

**Issue by karthikindia** [jelastic-jps/plesk#12]
hi there i am trying to install and configure plesk panel in jelastic. i am not able to view the contents of my vhost domain in public
please check the youtube attached - https://youtu.be/1nZjnqinc0U
kindly advice

**Comment by lazarenkoalexey** [comment]
Hi,
Sorry for the late response.
While creating a new domain you have an ability to choose a IP address which will be used in the tab 'Webspace settings'. By default it was an internal IP address cause it the first address which is defined by Plesk.
We have fixed the issue and now by default will be set an external IP address.
The current fix is already available in our Marketplace in a new installations
